name: 'Trivy integration with GitHub'
author: 'Kevin Nika'
description: 'A way to output results of Trivy VM scan in GitHub Checks.'
inputs:
  image-ref:  # id of input
    description: 'name of built container image'
    required: true
  repo_token:
    description: 'Github repo token'
    required: true
#  pat: 
#    description: 'PAT'
#    required: true
runs:
  using: "composite"
  steps:
    - name: entry 
      uses: actions/checkout@v2
      with:
       repository: kevinnika1/Trivy-GitHubChecks-Action
       
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image-ref }}
        format: 'json'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        output: trivy-results.json
       
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
          
    - name: upload Trivy results to annotaions
      uses: yuzutech/annotations-action@v0.3.0
      with:
          repo-token: "${{ inputs.repo_token }}"
          title: 'Trivy Results'
          input: './trivyparsedresults.json'
